language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
install:
  - npm update
script:
  - npm run coveralls
after_success:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
