language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
install:
  - npm update
script:
  - npm run coveralls
after_success:
  - npm run build
#   branches:
#     only:
#       - master
  
